--刪除先前排程下載的資料
DELETE FROM ECSDB.OA_SC_BUSINESS_NOTES;


--更新OA_SYSTEMSETTING排程相關設定
DELETE FROM ECSDB.OA_SYSTEMSETTING WHERE SETTINGTYPE IN ('OA_SCHEDULE', 'OA_SC_BUSINESS_NOTES', 'OA_SCHEDULE_FLAG');

INSERT INTO ECSDB.OA_SYSTEMSETTING(SETTINGTYPE, STATUS, RESERVESTATUS, DESC, CREATOR, CREATEDATE)
VALUES
('OA_SCHEDULE', 'url', 'http://待確認填入/MegaAPI/Service/{source}?Clientid={clientid}&Itemid={itemid}', '直通國際連結', 'system', CURRENT TIMESTAMP),
('OA_SCHEDULE', 'clientid', '待確認填入', '直通國際clientid', 'system', CURRENT TIMESTAMP),
('OA_SC_BUSINESS_NOTES', 'source', 'GetItem', '條款source', 'system', CURRENT TIMESTAMP),
('OA_SC_BUSINESS_NOTES', 'AC1', 'F02B203A-B259-44BD-A968-36740FDF4AA6', '個人網路銀行業務服務契約約定條款 MegaIB Application Service Contract', 'system', CURRENT TIMESTAMP),
('OA_SC_BUSINESS_NOTES', 'AC2', 'D0CEEC72-3059-44D5-BC29-663E2151CE05', '履行個人資料保護法告知義務 Personal Information Protection Notification', 'system', CURRENT TIMESTAMP),
('OA_SC_BUSINESS_NOTES', 'PN1', 'B6B7085B-A465-4DD0-AE81-C7BFFEA44EE1', '信用卡簡訊密碼功能服務約定條款', 'system', CURRENT TIMESTAMP),
('OA_SCHEDULE_FLAG', 'BUSINESSNOTES', 'Y', '條款明細flag', 'system', CURRENT TIMESTAMP);


-- 新增PN3
INSERT INTO ECSDB.OA_SYSTEMSETTING(SETTINGTYPE, STATUS, RESERVESTATUS, DESC, CREATOR, CREATEDATE)
VALUES
('OA_SC_BUSINESS_NOTES', 'PN3', 'BD8079D6-2252-42E3-A215-2725B6690787', '信用卡網路預借現金交易注意事項', 'system', CURRENT TIMESTAMP);



